//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prova
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPedido
    {
        public int id_item_pedido { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<int> id_produto { get; set; }
        public Nullable<int> qtde { get; set; }
        public string subtotal { get; set; }
    }
}
