//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int id_produto { get; set; }
        public string nome_produto { get; set; }
        public string valor { get; set; }
    }
}
